# -*- coding: utf-8 -*-
"""STLviewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_BsPi1R3uWPBQ7sGunzIvqggjEDaOMn
"""

!pip install trimesh plotly

from google.colab import files
import trimesh
import plotly.graph_objects as go

# 1) Upload STL
uploaded = files.upload()  # choose your .stl file in the popup
stl_filename = list(uploaded.keys())[0]

# 2) Load mesh with trimesh
mesh = trimesh.load(stl_filename)

# 3) Extract vertices and faces
verts = mesh.vertices
faces = mesh.faces

# 4) Plot with Plotly (interactive 3D)
fig = go.Figure(
    data=[
        go.Mesh3d(
            x=verts[:, 0],
            y=verts[:, 1],
            z=verts[:, 2],
            i=faces[:, 0],
            j=faces[:, 1],
            k=faces[:, 2],
            opacity=1.0,
            flatshading=True,
        )
    ]
)

fig.update_layout(
    scene=dict(aspectmode="data"),
    margin=dict(l=0, r=0, t=0, b=0),
)

fig.show()
#choosefile: drop stl file